# Generated by Django 4.1.5 on 2023-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_resevation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
